// Fill out your copyright notice in the Description page of Project Settings.


#include "Map/P4StagePartBase.h"

#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"

#include "Components/BoxComponent.h"
#include "Monster/P4MonsterBase.h"
#include "NPC/P4NPCBase.h"

#include "NavMesh/NavMeshBoundsVolume.h"
//#include "Character/P4CharacterPlayer.h"

// Sets default values
AP4StagePartBase::AP4StagePartBase()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	USceneComponent* Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));

	RootComponent = Root;

	////ёуҪәЕН ҪәЖщ ҝөҝӘБцБӨҝл ҝА№ц·ҰұвҙЙАә өьИч ҫшАҪ ұЧАъ °Её®ёё БцБӨЗПҙВҝлөө.
	MonsterSpawner = CreateDefaultSubobject<UBoxComponent>(TEXT("MonsterSpawnArea"));
	MonsterSpawner->SetupAttachment(Root);
	MonsterSpawner->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	MonsterSpawner->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);

	//ёуҪәЕН »эјә Ж®ё®°Е »эјә.
	MonsterSpawnTrigger = CreateDefaultSubobject<UBoxComponent>(TEXT("MonsterSpawnTrigger"));
	MonsterSpawnTrigger->SetupAttachment(Root);
	MonsterSpawnTrigger->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	MonsterSpawnTrigger->SetCollisionResponseToAllChannels(ECR_Ignore);
	MonsterSpawnTrigger->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);

	//ёуҪәЕН »иБҰ Ж®ё®°Е »эјә.
	MonsterDeleteTrigger = CreateDefaultSubobject<UBoxComponent>(TEXT("MonsterDeleteTrigger"));
	MonsterDeleteTrigger->SetupAttachment(Root);
	MonsterDeleteTrigger->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	MonsterDeleteTrigger->SetCollisionResponseToAllChannels(ECR_Ignore);
	MonsterDeleteTrigger->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);

	//bMonsterSpawned = false;
}
// Called when the game starts or when spawned
void AP4StagePartBase::BeginPlay()
{
	Super::BeginPlay();

	//Map ЖДГч ҪәЖщ
	//AP4StagePartBase* Spawned 
	//	= GetWorld()->SpawnActor<AP4StagePartBase>(MapPart, FVector::ZeroVector,FRotator::ZeroRotator);
	//ёК ЖДГч ҪәЖщ
	SpawnMapPart();

	if (MonsterSpawnTrigger != nullptr)
	{
		MonsterSpawnTrigger->OnComponentBeginOverlap.AddDynamic(this, &AP4StagePartBase::OnSpawnTriggerBeginOverlap);
		//MonsterSpawnTrigger->OnComponentEndOverlap.AddDynamic(this, &AP4StagePartBase::OnSpawnTriggerEndOverlap);s
	}

	if (MonsterDeleteTrigger != nullptr)
	{
		//MonsterDeleteTrigger->OnComponentBeginOverlap.AddDynamic(this, &AP4StagePartBase::OnSpawnTriggerBeginOverlap);
		MonsterDeleteTrigger->OnComponentEndOverlap.AddDynamic(this, &AP4StagePartBase::OnDeleteTriggerEndOverlap);
	}

	//NavёЮҪГ ҪәЖщ.
	//SpawnNavMeshBounds();
}

// Called every frame
void AP4StagePartBase::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void AP4StagePartBase::OnSpawnTriggerBeginOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	//ҝА№ц·ҰЗС ҫЧЕН°Ў ЗГ·№АМҫоАОБц °Л»з.
	ACharacter* PlayerCharacter = UGameplayStatics::GetPlayerCharacter(this, 0);

	if (OtherActor != PlayerCharacter)
	{
		return;
	}

	//ёёҫа өО №иҝӯ ёрөО әсҫоАЦАёёй TRUE°Ў өИҙЩ.
	//bMonsterSpawned
	//	= (NPCs.IsEmpty() == false && Monsters.IsEmpty() == false);

	//if (Monsters.Num() > 0 || NPCs.Num() > 0)
	//{
	//	return;
	//}


	if (bMonsterSpawned == false)
	{
		SpawnMonsterInTrigger();
		SpawnNPCs();
	}
	//bMonsterSpawndҙВ ҫИАьАеДЎ.
	//if (bMonsterSpawned == false)
	//{
	//	//АПҙЬ ИӨҪГёрёЈҙП БцҝмБшё»ұв.
	//}
}


void AP4StagePartBase::OnDeleteTriggerEndOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	//ҝА№ц·ҰЗС ҫЧЕН°Ў ЗГ·№АМҫоАОБц °Л»з.
	ACharacter* PlayerCharacter = UGameplayStatics::GetPlayerCharacter(this, 0);

	if (OtherActor != PlayerCharacter)
	{
		return;
	}

	//ёуҪәЕН№иҝӯ јшИҜЗПёйјӯ »иБҰ.
	for (AP4MonsterBase* Monster : Monsters)
	{
		if (IsValid(Monster) == true)
		{
			Monster->Destroy();
		}
	}

	Monsters.Empty();

	for (AP4NPCBase* NPC : NPCs)
	{
		if (IsValid(NPC) == true)
		{
			NPC->Destroy();
		}
	}

	NPCs.Empty();

	bMonsterSpawned = false;
}

void AP4StagePartBase::SpawnMapPart()
{
	UWorld* world = GetWorld();

	if (MapPart == nullptr || world == nullptr)
	{
		return;
	}

	FActorSpawnParameters Params;

	Params.Owner = this;

	Params.SpawnCollisionHandlingOverride 
		= ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

	// АМ ЕёАП ActorАЗ А§ДЎ/ИёАь ұвБШАё·О ҪәЖщ
	const FVector  Loc = GetActorLocation();
	const FRotator Rot = GetActorRotation();

	AActor* MapActor = world->SpawnActor<AActor>(MapPart, Loc, Rot, Params);

	if (MapActor != nullptr)
	{
		// ЕёАП(АМ Actor)ҝЎ әЩҝ©іх°н ҪНАёёй:
		MapActor->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
	}

}

void AP4StagePartBase::SpawnNPCs()
{
	UWorld* world = GetWorld();

	if (world == nullptr)
	{
		return;
	}

	FActorSpawnParameters Params;
	Params.Owner = this;

	Params.SpawnCollisionHandlingOverride 
		= ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

	//1№ш NPC јТИҜ.
	if (NPCClass1 != nullptr)
	{
		const FVector SpawnLoc = GetActorLocation() + NPC1SpawnOffset;
		const FRotator SpawnRot = GetActorRotation() + NPC1SpawnRotation;

		AP4NPCBase* NPC1 = world->SpawnActor<AP4NPCBase>(NPCClass1, SpawnLoc, SpawnRot, Params);

		if (NPC1 != nullptr)
		{
			NPC1->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
			NPCs.Add(NPC1);
		}
	}

	if (NPCClass2 != nullptr)
	{
		const FVector SpawnLoc = GetActorLocation() + NPC2SpawnOffset;
		const FRotator SpawnRot = GetActorRotation() + NPC2SpawnRotation;

		AP4NPCBase* NPC2 = world->SpawnActor<AP4NPCBase>(NPCClass2, SpawnLoc, SpawnRot, Params);
		if (NPC2 != nullptr)
		{
			NPC2->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
			NPCs.Add(NPC2);
		}
	}
}

void AP4StagePartBase::SpawnMonsterInTrigger()
{
	if (bMonsterSpawned == true
		|| MonsterDeleteTrigger == nullptr
		|| MonsterClass == nullptr)
	{
		return;
	}

	UWorld* world = GetWorld();
	if (world == nullptr)
	{
		return;
	}

	// ҪәЖщ °№јц ·Јҙэ.
	const int32 Count = FMath::RandRange(MinMonsterCount, MaxMonsterCount);

	// Ж®ё®°Е №ЪҪә ұвБШАё·О ·Јҙэ А§ДЎ »Мұв (XYёё АЗ№М АЦ°Ф »зҝл)
	const FVector BoxOrigin = MonsterSpawner->GetComponentLocation();
	const FVector BoxExtent = MonsterSpawner->GetScaledBoxExtent();

	FActorSpawnParameters Params;
	Params.Owner = this;
	Params.SpawnCollisionHandlingOverride =
		ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

	for (int32 i = 0; i < Count; ++i)
	{
		// 1) XYҙВ ·Јҙэ, ZҙВ АПҙЬ №ЪҪә А§ВКҝЎјӯ ҪГАЫ
		FVector RandLoc = UKismetMathLibrary::RandomPointInBoundingBox(BoxOrigin, BoxExtent);
		RandLoc.Z = BoxOrigin.Z + BoxExtent.Z + 5000.f;   // А§ВК ҝ©АҜ

		// 2) А§ҝЎјӯ ҫЖ·Ў·О ¶уАО Ж®·№АМҪәЗШјӯ "БшВҘ №ЩҙЪ" ГЈұв
		FHitResult Hit;
		FCollisionQueryParams QueryParams;
		QueryParams.bTraceComplex = true;
		QueryParams.AddIgnoredActor(this); // ЕёАП ҫЧЕН АЪҪЕАә №«ҪГ (ҝшЗПёй ёуҪәЕН, ЗГ·№АМҫо өо ГЯ°Ў)

		const FVector TraceStart = RandLoc;
		const FVector TraceEnd = RandLoc - FVector(0.f, 0.f, 20000.f);

		if (world->LineTraceSingleByChannel(
			Hit,
			TraceStart,
			TraceEnd,
			ECC_Visibility,
			QueryParams))
		{
			// 3) ёВАә °ч А§·О ҫа°Ј ¶зҝцјӯ ҪәЖщ (Бцёй °ьЕл №жБц)
			RandLoc = Hit.ImpactPoint + FVector(0.f, 0.f, 10.f);
		}
		else
		{
			// №ЩҙЪА» ёш ГЈҫТАёёй ұЧіЙ АМ А§ДЎҙВ №цё®°н ҙЩАҪАё·О
			UE_LOG(LogTemp, Warning, TEXT("SpawnMonsterInTrigger: Failed to find ground, skip one spawn"));
			continue;
		}

		const FRotator RandRot = FRotator::ZeroRotator;

		AP4MonsterBase* Monster = world->SpawnActor<AP4MonsterBase>(
			MonsterClass,
			RandLoc,
			RandRot,
			Params
		);

		if (Monster != nullptr)
		{
			Monster->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
			Monsters.Add(Monster);
		}
	}

	bMonsterSpawned = true;
}

